### PR TITLE
Support for Azure AD mapped users

### PR DESCRIPTION
**Pull request by tkielar-pgs**

### CODE REVIEW

**Comment by tmeckel** [comment]
@tkielar-pgs will the PR be out of draft status soon? Would be awesome because we'd like to use the functionality in a customer project.

**Comment by tkielar-pgs** [comment]
> @tkielar-pgs will the PR be out of draft status soon? Would be awesome because we'd like to use the functionality in a customer project.

Sorry, been swamped with work lately... It still needs some work, as it turns out, SPs need special treatment. Hopefully I'll have time to finish it within the next 1-2 weeks.

**Comment by tmeckel** [comment]
@tkielar-pgs thanks for keeping me posted! Highly appreciated :+1 Any help needed?

**Comment by tmeckel** [comment]
@tkielar-pgs YEAH 👍🏼 Great to have support for Azure AD mapped users!! 😁 🚀

**Pull request merged**
